services:
  - type: web
    name: fapet
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://fapet.onrender.com
      - key: SESSION_DRIVER
        value: database
