services:
  - type: web
    name: fapet
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_URL
        value: https://fapet.onrender.com
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: APP_KEY
        value: "base64:WlGA6UG3nQ7yoErq+egY9lymCANyOK1YujuWu8tFjLk="
